services:
  - type: web
    name: yappuccino
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn blogpost.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        sync: false
      - key: B2_ACCESS_KEY_ID
        sync: false
      - key: B2_SECRET_ACCESS_KEY
        sync: false
      - key: B2_BUCKET_NAME
        sync: false
      - key: B2_REGION
        sync: false