services:
  - type: web
    name: yappuccino
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn blogpost.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: "blogpost.production"
      - key: DATABASE_URL
        fromDatabase:
          name: yappuccino_db
          property: connectionString
      - key: B2_ACCESS_KEY_ID
        sync: false
      - key: B2_SECRET_ACCESS_KEY
        sync: false
      - key: B2_BUCKET_NAME
        sync: false
      - key: B2_REGION
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false

databases:
  - name: yappuccino_db
    databaseName: yappuccino_db
    user: yappuccino_user