# Generated by Django 5.2.1 on 2025-05-18 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_is_repost_post_original_post_post_view_count_and_more'),
        ('blog', '0004_create_default_tags'),
    ]

    operations = [
    ]
