# Generated by Django 5.2.1 on 2025-05-19 16:07

from django.db import migrations, models
from django.utils.text import slugify


def generate_unique_slugs(apps, schema_editor):
	"""
    Generate unique slugs for existing tags
    """
	# Get the historical Tag model
	Tag = apps.get_model('blog', 'Tag')

	for tag in Tag.objects.all():
		# Create base slug
		base_slug = slugify(tag.name)
		slug = base_slug
		counter = 1

		# Find a unique slug
		while Tag.objects.filter(slug=slug).exclude(id=tag.id).exists():
			slug = f"{base_slug}-{counter}"
			counter += 1

		# Save the unique slug
		tag.slug = slug
		tag.save()


class Migration(migrations.Migration):
	dependencies = [
		('blog', '0005_merge_20250519_0111'),
	]

	operations = [
		# Step 1: Add the slug field allowing NULL values temporarily
		migrations.AddField(
			model_name='tag',
			name='slug',
			field=models.SlugField(max_length=50, null=True, blank=True),
		),

		# Step 2: Run data migration to populate slugs
		migrations.RunPython(generate_unique_slugs),

		# Step 3: Make the field required and unique
		migrations.AlterField(
			model_name='tag',
			name='slug',
			field=models.SlugField(max_length=50, unique=True),
		),
	]