# Generated by Django 5.2.1 on 2025-05-19 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_add_tag_slugs'),
        ('blog', '0007_add_tag_slug_field'),
    ]

    operations = [
    ]
