# Generated by Django 5.2.1 on 2025-05-19 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_tagalias'),
    ]

    operations = [
    ]
